const Filter_Settings = [
   { name: "brightness", value: 100, min: 0, max: 200, unit: "%" },
   { name: "contrast", value: 100, min: 0, max: 200, unit: "%" },
   { name: "saturate", value: 100, min: 0, max: 200, unit: "%" },
   { name: "hue-rotate", value: 0, min: 0, max: 360, unit: "deg" },
   { name: "blur", value: 0, min: 0, max: 20, unit: "px" },
   { name: "grayscale", value: 0, min: 0, max: 100, unit: "%" },
   { name: "Sepia", value: 0, min: 0, max: 100, unit: "%" },
   { name: "opacity", value: 100, min: 0, max: 100, unit: "%" },
   { name: "Invert", value: 0, min: 0, max: 100, unit: "%" },
];

const Filter_Presets = {
   normal: {
      brightness: 100,
      contrast: 100,
      saturate: 100,
      "hue-rotate": 0,
      blur: 0,
      grayscale: 0,
      Sepia: 0,
      opacity: 100,
      Invert: 0,
   },

   drama: {
      brightness: 95,
      contrast: 140,
      saturate: 130,
      "hue-rotate": 0,
      blur: 0,
      grayscale: 0,
      Sepia: 5,
      opacity: 100,
      Invert: 0,
   },

   vintage: {
      brightness: 105,
      contrast: 90,
      saturate: 80,
      "hue-rotate": -10,
      blur: 0,
      grayscale: 10,
      Sepia: 30,
      opacity: 100,
      Invert: 0,
   },

   cinematic: {
      brightness: 95,
      contrast: 125,
      saturate: 110,
      "hue-rotate": -5,
      blur: 0,
      grayscale: 0,
      Sepia: 8,
      opacity: 100,
      Invert: 0,
   },

   moody: {
      brightness: 90,
      contrast: 135,
      saturate: 85,
      "hue-rotate": 0,
      blur: 0,
      grayscale: 5,
      Sepia: 10,
      opacity: 100,
      Invert: 0,
   },

   warm: {
      brightness: 105,
      contrast: 110,
      saturate: 120,
      "hue-rotate": -15,
      blur: 0,
      grayscale: 0,
      Sepia: 15,
      opacity: 100,
      Invert: 0,
   },

   cool: {
      brightness: 100,
      contrast: 115,
      saturate: 110,
      "hue-rotate": 15,
      blur: 0,
      grayscale: 0,
      Sepia: 0,
      opacity: 100,
      Invert: 0,
   },

   blackAndWhite: {
      brightness: 100,
      contrast: 130,
      saturate: 0,
      "hue-rotate": 0,
      blur: 0,
      grayscale: 100,
      Sepia: 0,
      opacity: 100,
      Invert: 0,
   },

   faded: {
      brightness: 110,
      contrast: 85,
      saturate: 90,
      "hue-rotate": 0,
      blur: 0,
      grayscale: 5,
      Sepia: 10,
      opacity: 100,
      Invert: 0,
   },

   cyberpunk: {
      brightness: 105,
      contrast: 150,
      saturate: 160,
      "hue-rotate": 25,
      blur: 0,
      grayscale: 0,
      Sepia: 0,
      opacity: 100,
      Invert: 0,
   },
};

export default { Filter_Settings, Filter_Presets };
